- lib/selleckt.js
This change stops multiple selleckts from preventing the user scrolling the element behind, on when the multiple selleckt element is closed.
Waiting for:
> Allowing event propgation and default behaviour on mouse scrolling

- .travis.yml
- Gruntfile.js
- README.md
I created an "Open Source" account, which should now fix the badges,
as well as enable us to create sub-accounts for other Brandwatch
OS repos.
> Changed Saucelabs account

- Gruntfile.js
- README.md
- demo/css/selleckt.css
- demo/index.html
- lib/selleckt.js
- test/index.html
- test/lib/mustache.js
- test/selleckt.tests.js
@spmason this introduces the ability to dynamically add and remove items to Selleckt.
It uses a Dom Mutation Observer to watch changes to the underlying select element. Those changes can be direct in the dom, or instead via the new 'add/remove' item(s) methods. This should allow for flexibility from the implementor.
I had to change the public api as part of this, as there was a method called `removeItem` in MultiSelleckt that actually 'unselected' an item. This was a naming clash with the new methods.
I've also moved to mustache 0.8 for its better partials support.
> Selleckt async

- demo/index.html
The "FancySelleckt" demo did not work properly because of an incorrect
class name on the item selection template
> Fix demo page

- README.md
- demo/css/selleckt.css
- demo/index.html
- dist/selleckt-legacy-shim.js
- dist/selleckt.js
- karma.conf.js
- lib/MultiSelleckt.js
- lib/SellecktPopup.js
- lib/SingleSelleckt.js
- lib/TEMPLATES.js
- lib/selleckt.js
- lib/shim/selleckt-legacy-shim.js
- test/.jshintrc
- test/specs/MultiSelleckt.specs.js
- test/specs/SellecktPopup.specs.js
- test/specs/SingleSelleckt.specs.js
- test/unit.js
I felt that Selleckt was getting pretty overcomplicated when it came to
positioning the popup containing the options.
This PR refactors the popup out into a separate class. The popup itself
now attaches to the DOM inside the body element, and adds a handler so
that it stays aligned with the opening element when the window resizes.
One other advantage of the popup being separate is that now we dont need
to track the state of the items inside it - we simply blow the whole popup
away when we close (or search within!) it. This makes it a lot easier to
reason with in the code.
> Selleckt popup

- dist/selleckt.js
- lib/SingleSelleckt.js
- test/specs/SingleSelleckt.specs.js
Tweak for item filtering:
1. If the "hideSelectedItem" property is true, the popup should not
refresh with the selected item visible.
2. Additionally, the 'optionsFiltered' event should always be triggered
when the popup is refreshed.
> Item filtering fix

- karma.conf.js
- package.json
Missing/Superfluous dependencies were causing `npm test` to fail.
> Selleckt karma fix

- dist/selleckt.js
- lib/SingleSelleckt.js
- test/specs/SingleSelleckt.specs.js
The convenience function `selectItemByValue` should not call `selectItem` if an item with the supplied value is not found in the collection.
> Select item by value fix

- dist/selleckt.js
- lib/MultiSelleckt.js
- lib/SingleSelleckt.js
- test/specs/MultiSelleckt.specs.js
- test/specs/SingleSelleckt.specs.js
Hey @grahamscott,
so that we are able to distinguish between programmatic changes and user input changes `selleckt.selectItem(123, {silent: true})` won't trigger the event `itemSelected` anymore as it did before.
Thanks
> NRP-2976 do not emit event on programmatic changes

- demo/index.html
- dist/selleckt.js
- lib/SellecktPopup.js
- test/specs/SellecktPopup.specs.js
Hi @codazzo and @grahamscott ,
I have to define a custom <code>sellecktItem.template</code> for my implementation of <code>selleckt</code> (I need to put the content to html to style it properly). I noticed that when I filter the list out I lose all the information about the item's model different than <code>label</code> and <code>value</code>.
In this PR I'm fixing this issue by extending the data passed to the item renderer with attributes of the model for which the given row is displayed.
To check how it works, please play with the __Fancy select__ section on the demos page.
> Rendering of filtered items

- dist/selleckt.js
- lib/MultiSelleckt.js
- lib/SingleSelleckt.js
- package.json
- test/specs/MultiSelleckt.specs.js
- test/unit.js
When `hideSelectedItem` was set to `true` for MultiSelleckt the current selection would not show up in the dropdown. However, the selected values would suddenly appear in the dropdown when doing a search. Fix this so that MultiSelleckt behaves the same as SingleSelleckt.
> Fix hide selected items for multipleselleckt search

- dist/selleckt.js
- lib/MultiSelleckt.js
- test/specs/MultiSelleckt.specs.js
Change default setting for `hideSelectedItem` to `true` for `MultiSelleckt`.
> Hide selected items by default for multiselleckt

- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/SellecktPopup.js
- test/specs/SellecktPopup.specs.js
Hi @grahamscott,
This code prevents the <code>click</code> event from bubbling up to <code>body</code> element.
> Stopped the 'click' event propagation when an item/search field is clicked

- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/SingleSelleckt.js
- test/specs/MultiSelleckt.specs.js
- test/specs/SingleSelleckt.specs.js
Currently, when selleckt is re-initialized on a `select` element *after* the user has modified the selection then re-initializing will cause selleckt to display the wrong selected items (it displays the select's initial state rather than the user's selection).
This is caused by checking the selected state of option elements via `attr` rather than `prop`.
> Use `prop` instead of `attr` to check whether an option element is selected

- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/SingleSelleckt.js
- test/specs/SingleSelleckt.specs.js
Adds support for (optional) multiple aliases for each of the `selleckt` option items.
Useful for filtering where an alias can't be part of an option label but should still match the search input.
> Support for aliases in selleckt

- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/SellecktPopup.js
- test/specs/SellecktPopup.specs.js
On a tiny screen with a very long list of items in a `selleckt` dropdown, there is sometimes not enough vertical space on either side of an `opener` to display the full list of items. In this case, a dropdown should be positioned on the bottom as browsers are more likely to provide extra scrolling in that case.
> When not enough space for dropdown on either side, prefer bottom placement, not top

- karma.conf-saucelabs-legacyselleckt.js
> The pull request removes IE8 from the list of SauceLabs launchers.
IE8 won't be supported any more by legacy-selleckt. Currently the demo pages show that at  it still works. The compatibility won't however be actively developed.
The tests however fail on IE8 with an error regarding the positioning.
Furthermore IE8 throws an error with `'this.$popup' is null or not an object` at `selleckt-legacy.js:643`.
> Drop IE8 support: remove IE8 from SauceLabs launchers.

- .eslintrc
- README.md
- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/SellecktPopup.js
- lib/SingleSelleckt.js
- test/specs/SellecktPopup.specs.js
- test/specs/SingleSelleckt.specs.js
Selleckt evaluates if there is enough space available below the `select` element by using the popup height at the time it is opened.  
When selleckt is used with search, the height of the popup depends on the returned list of results and is constrained by a `max-height` property on the list of elements. 
This enhancement adds a `maxHeightPopupPositioning` option for the cases where you want selleckt to use the maximum height of the popup to evaluate the flipping position.
> add option to evaluate popup flipping position when popup height is dynamic

- README.md
- demo/index.html
- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/MicroEvent.js
- lib/SingleSelleckt.js
- test/specs/MultiSelleckt.specs.js
- test/specs/SellecktPopup.specs.js
- test/specs/SingleSelleckt.specs.js
In this PR:
- `$#bind` and `$#unbind` are deprecated in jQuery 3, so I added `on` and `off` aliases to `MicroEvent#bind` and `#unbind` for consistency sake
More details: 
https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnbind-is-deprecated
> Add jQuery 3.0.0 compat layer

- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/MultiSelleckt.js
- test/specs/MultiSelleckt.specs.js
Back in https://github.com/BrandwatchLtd/selleckt/pull/78 I missed that `MultiSelleckt` also has an `unselectItem(...)`. There an `itemUnselected` is still triggering regardless if`options.silent` is  passes. 
This PR aligns the [behaviour of `selectItem(...)`](https://github.com/BrandwatchLtd/selleckt/blob/master/lib/MultiSelleckt.js#L105-L110) and `unselectItem(...)` when `options.silent` is passed.
> Do not trigger itemUnselected when options.silent is passed

- README.md
- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/SellecktPopup.js
- lib/SingleSelleckt.js
- test/specs/SellecktPopup.specs.js
- test/specs/SingleSelleckt.specs.js
In Analytics, we used `selleckt` with a `defaultSearchTerm` which was manually added to the search input.
It turned up that this introduces an inconsistency between the items displayed on popup creation and the ones displayed after the search is used, the latter being filtered and sorted by `_filterItems` in `_refreshPopupWithSearchHits`.
This PR introduces a `defaultSearchTerm` option which is taken into account when opening the popup and is then used to filter (and sort) the search items.
> NRP-4276 Add default search term option

- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/SellecktPopup.js
- test/specs/SellecktPopup.specs.js
We noticed in Analytics one case where the `enableSearch` option was misused (the popup template did not contain any search input), which resulted in a javascript error.
This PR aims at fixing the line which throws an error so that other similar cases don't break.
> NRP-4276 Fix breaking line when enable search is misused

- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/SingleSelleckt.js
- test/specs/SingleSelleckt.specs.js
When implementing the `defaultSearchTerm` option, a bug was introduced. 
Every time a search was done and the popup was re-opened, the last search term was getting overwritten by the default search term.
This PR fixes this bug by resetting the defaultSearchTerm to the last search performed.
> NRP-4276 Fix query persistence

- dist/selleckt-legacy.js
- dist/selleckt.js
- lib/MultiSelleckt.js
- lib/SingleSelleckt.js
- test/specs/MultiSelleckt.specs.js
When the popup is open and an item is unselected by the user, the unselected item should be put back in the search items.
This PR fixes this behaviour.
> Fix results filtering after unselect
